services:
  vite:
    image: node:20-alpine
    working_dir: /home/node/app
    entrypoint: npm run dev
    networks:
      - traefik
    volumes:
      - "./:/home/node/app"
      - "../hankit-ui:/home/node/hankit-ui"
    labels:
      - "traefik.http.routers.betterprotect-ui-vite.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.betterprotect-ui-vite.tls=true"
      - "traefik.http.routers.betterprotect-ui-vite.tls.certresolver=lets-encrypt"
      - "traefik.http.services.betterprotect-ui-vite.loadbalancer.server.port=8080"
      - "traefik.http.services.betterprotect-ui-vite.loadbalancer.server.scheme=http"

networks:
  traefik:
    external: true